# Generated by Django 4.1.6 on 2023-03-19 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
    ]
